"""`resolve_derived_conflict` on a repo WITHOUT `scripts/export_guard.py`
(the inventory backend): repos that carry `scripts/check_release_manifest.py`
regenerate the whole manifest with `--write` and verify with `--strict`.

Root cause this covers (found live 2026-09-04): the resolver hard-required
`scripts/export_guard.py`, so on the public working repo EVERY manifest-only
PR conflict failed mechanically with step 'regenerate' and escalated a
finished task to a human — three tasks in one day. The fix is gated here on
real end-to-end git fixtures, not mocks.

The fixture copies the REAL `scripts/check_release_manifest.py` from this
repo into the scratch repo — the tool is stdlib-only by its own contract and
roots itself via `git rev-parse --show-toplevel` from its own location, so it
runs unmodified in the fixture. `_inventory_argv()` uses `sys.executable` on
an unfrozen build, so no monkeypatch is needed: the tests exercise the exact
argv production runs here.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from no_human.vcs import derived_conflict as dc

_REAL_TOOL = Path(__file__).resolve().parents[1] / "scripts" / "check_release_manifest.py"


def _run(args: list[str], *, cwd) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)


def _git(cwd, *args: str) -> subprocess.CompletedProcess:
    return _run(["git", *args], cwd=cwd)


def _write_manifest(work: Path) -> None:
    r = _run([sys.executable, "scripts/check_release_manifest.py", "--write"],
             cwd=work)
    assert r.returncode == 0, f"fixture --write failed:\n{r.stdout}{r.stderr}"


def _repo(tmp_path: Path) -> Path:
    """From-scratch repo + bare origin: one source file, the REAL inventory
    tool at scripts/check_release_manifest.py, NO export_guard.py, and a
    manifest generated by the tool itself."""
    origin = tmp_path / "origin.git"
    work = tmp_path / "work"
    _run(["git", "init", "-q", "--bare", str(origin)], cwd=tmp_path)
    _run(["git", "init", "-q", "-b", "main", str(work)], cwd=tmp_path)
    _git(work, "config", "user.email", "a@example.com")
    _git(work, "config", "user.name", "a")
    (work / "src").mkdir()
    (work / "src" / "base.py").write_text("base\n", encoding="utf-8")
    (work / "scripts").mkdir()
    shutil.copy(_REAL_TOOL, work / "scripts" / "check_release_manifest.py")
    _git(work, "add", "-A")
    _git(work, "commit", "-qm", "init")
    _write_manifest(work)
    _git(work, "add", "RELEASE_MANIFEST.txt")
    _git(work, "commit", "-qm", "pin inventory")
    _git(work, "remote", "add", "origin", str(origin))
    _git(work, "push", "-qu", "origin", "main")
    return work


def _worktree(work: Path, dest: Path, branch: str, base: str = "main") -> None:
    _git(work, "worktree", "add", "-q", "-b", branch, str(dest), base)


def _push_branch(work: Path, wt: Path, branch: str) -> None:
    sha = _git(wt, "rev-parse", "HEAD").stdout.strip()
    _git(work, "push", "-q", "origin", f"{sha}:refs/heads/{branch}")
    _git(work, "branch", "-q", "--set-upstream-to", f"origin/{branch}", branch)


def _conflicting_fixture(tmp_path: Path) -> tuple[Path, str]:
    """feature and main each add a different file and regenerate the whole
    manifest — two full rewrites of the same file collide for real."""
    work = _repo(tmp_path)

    wt = tmp_path / "wt_feature"
    _worktree(work, wt, "feature")
    (wt / "src" / "on_feature.py").write_text("on feature\n", encoding="utf-8")
    _git(wt, "add", "src/on_feature.py")
    _git(wt, "commit", "-qm", "add on_feature.py")
    _write_manifest(wt)
    _git(wt, "add", "RELEASE_MANIFEST.txt")
    _git(wt, "commit", "-qm", "pin on_feature.py")
    _push_branch(work, wt, "feature")

    (work / "src" / "on_main.py").write_text("on main\n", encoding="utf-8")
    _git(work, "add", "src/on_main.py")
    _git(work, "commit", "-qm", "add on_main.py")
    _write_manifest(work)
    _git(work, "add", "RELEASE_MANIFEST.txt")
    _git(work, "commit", "-qm", "pin on_main.py")
    _git(work, "push", "-q", "origin", "HEAD:refs/heads/main")

    base_tip = _git(work, "rev-parse", "origin/main").stdout.strip()
    return work, base_tip


async def test_manifest_conflict_resolves_on_the_inventory_backend(tmp_path):
    work, base_tip = _conflicting_fixture(tmp_path)

    # sanity: the conflict is real and confined to the manifest.
    paths = await dc.conflicting_paths(str(work), "main", "feature")
    assert paths == {"RELEASE_MANIFEST.txt"}

    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert res.ok, f"step={res.step}: {res.detail}"
    assert res.pushed_sha

    # The pushed merge's manifest carries BOTH sides' files and verifies.
    check = tmp_path / "check"
    _run(["git", "clone", "-q", "-b", "feature", str(work / ".git"), str(check)],
         cwd=tmp_path)
    _git(check, "checkout", "-q", res.pushed_sha)
    manifest = (check / "RELEASE_MANIFEST.txt").read_text(encoding="utf-8")
    assert "src/on_feature.py" in manifest and "src/on_main.py" in manifest
    verify = _run([sys.executable, "scripts/check_release_manifest.py"],
                  cwd=check)
    assert verify.returncode == 0, verify.stdout + verify.stderr


def test_a_repo_with_neither_tool_fails_closed(tmp_path):
    work = tmp_path / "bare-work"
    _run(["git", "init", "-q", "-b", "main", str(work)], cwd=tmp_path)
    _git(work, "config", "user.email", "a@example.com")
    _git(work, "config", "user.name", "a")
    (work / "f.txt").write_text("x\n", encoding="utf-8")
    _git(work, "add", "-A")
    _git(work, "commit", "-qm", "init")

    res = dc.resolve_derived_conflict(str(work), "feature", "HEAD")
    assert not res.ok and res.step == "regenerate"
    assert "check_release_manifest.py" in res.detail


def test_classification_eligibility_fails_closed_without_export_guard(tmp_path):
    work = _repo(tmp_path)
    res = dc.resolve_derived_conflict(
        str(work), "feature", "HEAD",
        eligible=dc.DERIVED_ARTEFACTS | {"EXPORT_CLASSIFICATION.txt"})
    assert not res.ok and res.step == "regenerate"
    # A distinctive fragment of the NEW refusal — the tmp_path directory name
    # contains "classification", so a loose substring check would pass on the
    # OLD message too (review finding on the first revision of this test).
    assert "cannot reconcile classification counts" in res.detail


# --- `_inventory_argv` delegates to the one shared interpreter resolver
# --- (`proc.real_python`) instead of re-writing the PyInstaller-frozen
# --- fallback inline a fifth time (issue #402). These pin the delegation
# --- itself, not just the output, because before this fix the module-level
# --- inline fallback already produced an identical-looking argv on the
# --- happy path — only swapping the shared resolver proves it is actually
# --- being called. ----------------------------------------------------------


def test_inventory_argv_delegates_to_the_shared_real_python(monkeypatch):
    monkeypatch.setattr(dc, "real_python", lambda *a: "/opt/marker/python")
    assert dc._inventory_argv() == [
        "/opt/marker/python", "scripts/check_release_manifest.py"]


def test_inventory_argv_falls_back_to_the_python3_literal_when_unresolved(
        monkeypatch):
    """Unlike every other `real_python` call site, this one never fails
    closed — `resolve_derived_conflict`'s caller has no `None` branch — so
    an unresolved interpreter still produces a runnable argv."""
    monkeypatch.setattr(dc, "real_python", lambda *a: None)
    assert dc._inventory_argv() == [
        "python3", "scripts/check_release_manifest.py"]


def test_inventory_argv_never_returns_the_frozen_binary_when_frozen(
        monkeypatch, tmp_path):
    """End-to-end through the real resolver (not the delegation seam above):
    frozen shape, `sys.executable` an `nh` stub, PATH holds a python3 — the
    produced argv[0] must be that PATH python3, never the frozen binary."""
    nh = tmp_path / "nh"
    nh.write_text("", encoding="utf-8")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(nh))
    monkeypatch.setattr(shutil, "which",
                         lambda n: f"/usr/bin/{n}" if n == "python3" else None)
    argv = dc._inventory_argv()
    assert argv[0] == "/usr/bin/python3"
    assert argv[0] != str(nh)


async def test_a_write_refusal_is_a_regenerate_failure_not_a_push(tmp_path):
    """Plant a classification file so the tool's own `--write` refuses with
    exit 2 (in this fixture, via its load_unpinnable Refused branch — no
    build_public_export.py beside it; the "would pin N drop-classified
    path(s)" branch exits 2 identically): the resolver must report step
    'regenerate' and push nothing — the same fixture as the happy path,
    one flip."""
    work, base_tip = _conflicting_fixture(tmp_path)
    (work / "EXPORT_CLASSIFICATION.txt").write_text("ship 1 src/base.py\n",
                                                    encoding="utf-8")
    _git(work, "add", "EXPORT_CLASSIFICATION.txt")
    _git(work, "commit", "-qm", "classification appears")
    _git(work, "push", "-q", "origin", "HEAD:refs/heads/main")
    base_tip = _git(work, "rev-parse", "origin/main").stdout.strip()

    before = _git(work, "rev-parse", "origin/feature").stdout.strip()
    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert not res.ok and res.step == "regenerate"
    after = _git(work, "rev-parse", "origin/feature").stdout.strip()
    assert before == after  # nothing was pushed


def test_a_regenerate_failure_detail_keeps_the_traceback_last_line(
        tmp_path, monkeypatch):
    """A failed `--write` subprocess's stdout+stderr is capped via `_cap`
    before landing in `DerivedResolution.detail`. A Python traceback carries
    its exception type/message on the LAST line — the exact field defect
    this reproduces is a Python-3.9 interpreter's `Path.write_text` raising
    `TypeError: ... unexpected keyword argument 'newline'` at the end of a
    long frame list. `_cap` must preserve that last line, not just the head,
    or the escalation shows only stack frames with the real error cut off."""
    work, base_tip = _conflicting_fixture(tmp_path)

    frames = "  File \"x.py\", line 1, in f\n" * 400  # far over _STDERR_CAP
    traceback_text = (
        "Traceback (most recent call last):\n" + frames
        + "TypeError: write_text() got an unexpected keyword argument 'newline'\n"
    )
    assert len(traceback_text) > 4000, (
        "fixture must actually exceed the cap or this test proves nothing")
    fake_write_proc = subprocess.CompletedProcess(
        args=[], returncode=1, stdout=traceback_text, stderr="")

    def fake_run_inventory(worktree_path, subargs, *, timeout):
        assert subargs == ["--write"], (
            "a failed --write must never reach --strict verification")
        return fake_write_proc

    monkeypatch.setattr(dc, "_run_inventory", fake_run_inventory)

    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert not res.ok and res.step == "regenerate"
    assert res.detail.endswith(
        "TypeError: write_text() got an unexpected keyword argument 'newline'")
