"""Coverage rejection: derived artefacts are never required, and a directory
listing that NAMES a cut file references it.

Five reviewer verdicts were discarded as "reviewer reached a verdict without
referencing truncated changed file(s): RELEASE_MANIFEST.txt, ..." — a file
regenerated by `scripts/check_release_manifest.py --write` and byte-checked by
CI, with nothing in it to judge. The other cut paths on one of them were
fixture copies the reviewer surfaced only through a directory listing, which
the input-only tracker could not see.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from no_human.agent.claude_backend import AgentEvent, AgentResult
from no_human.review.diff_coverage import (
    COVERAGE_REJECTION_PREFIX,
    InspectionTracker,
    budget_diff,
    coverage_rejection_paths,
)
from no_human.review.reviewer import AdversarialReviewer, ReviewerUnavailable
from no_human.vcs.derived_conflict import DERIVED_ARTEFACTS

_CASE_DIR = "eval/reviewer_recall/cases/some-case/base"


def _chunk(path: str, body: str) -> str:
    return (
        f"diff --git a/{path} b/{path}\n"
        f"--- a/{path}\n"
        f"+++ b/{path}\n"
        "@@ -1 +1 @@\n-old\n+" + body + "\n"
    )


def _cut_manifest_and_source() -> list[str]:
    """A real capped diff whose cut set is the manifest AND a source file."""
    raw = _chunk("RELEASE_MANIFEST.txt", "M" * 4000) + _chunk(
        "src/big.py", "S" * 4000)
    _rendered, cut = budget_diff(raw, 2000)
    assert sorted(cut) == ["RELEASE_MANIFEST.txt", "src/big.py"], cut
    return cut


def _passing_block() -> str:
    return (
        "REVIEW_JSON_START\n"
        '{"passed": true, "items": [{"label": "ok", "passed": true, '
        '"severity": "low", "evidence": "covered"}]}\n'
        "REVIEW_JSON_END\n"
    )


class _Backend:
    """Emits `events` each round, then a passing verdict."""

    model = "test"

    def __init__(self, events: list[AgentEvent]):
        self.events = events
        self.calls = 0

    async def run(self, prompt, *, cwd, max_turns, effort=None, on_event=None, **kwargs):
        self.calls += 1
        for event in self.events:
            if on_event is not None:
                on_event(event)
        return AgentResult(final_text=_passing_block(), num_turns=1, is_error=False,
                           tokens_used=10, session_id="cov", stop_reason="end_turn")


def _read(path: str) -> AgentEvent:
    return AgentEvent("tool_use", tool_name="Read", tool_input={"file_path": path})


def _ls(directory: str, tool_use_id: str = "ls1") -> AgentEvent:
    return AgentEvent("tool_use", tool_name="Bash",
                      tool_input={"command": f"ls -la {directory}"},
                      meta={"tool_use_id": tool_use_id})


def _result(output: str, tool_use_id: str = "ls1", *, is_error: bool = False) -> AgentEvent:
    return AgentEvent("tool_result", output=output,
                      meta={"tool_use_id": tool_use_id, "is_error": is_error})


# ── 1. the derived manifest is never required ───────────────────────────── #


def test_the_manifest_is_the_shared_derived_set_not_a_copy():
    assert "RELEASE_MANIFEST.txt" in DERIVED_ARTEFACTS


async def test_a_verdict_stands_when_only_the_cut_source_file_was_referenced(tmp_path):
    cut = _cut_manifest_and_source()
    tracker = InspectionTracker(cut)
    tracker.note_event(_read("src/big.py"))
    assert tracker.rejection() == ""

    backend = _Backend([_read("src/big.py")])
    decision = await AdversarialReviewer(backend=backend, timeout=1)._agent_review(
        "prompt", tmp_path, max_turns=1, required_inspections=cut)
    assert decision.passed is True
    assert backend.calls == 1


def test_a_nested_file_named_like_the_manifest_is_still_required():
    tracker = InspectionTracker(["docs/RELEASE_MANIFEST.txt"])
    assert tracker.unreferenced() == ["docs/RELEASE_MANIFEST.txt"]


# ── 2. an unreferenced cut source file is rejected exactly as before ────── #


async def test_an_unreferenced_cut_source_file_is_still_rejected(tmp_path):
    cut = _cut_manifest_and_source()
    tracker = InspectionTracker(cut)
    tracker.note_event(_read("RELEASE_MANIFEST.txt"))
    assert tracker.unreferenced() == ["src/big.py"]
    assert tracker.rejection() == (
        "reviewer reached a verdict without referencing truncated "
        "changed file(s): src/big.py")
    # 4. the round-2 feed-back still classifies it by the unchanged prefix.
    assert tracker.rejection().startswith(COVERAGE_REJECTION_PREFIX)
    assert coverage_rejection_paths(tracker.rejection()) == ["src/big.py"]

    backend = _Backend([])
    with pytest.raises(ReviewerUnavailable):
        await AdversarialReviewer(backend=backend, timeout=1)._agent_review(
            "prompt", tmp_path, max_turns=1, required_inspections=cut)
    assert backend.calls == 2


# ── 3. a directory listing references a cut file only if it names it ───── #


def test_a_listing_that_names_the_cut_file_references_it():
    tracker = InspectionTracker([f"{_CASE_DIR}/fixture.py"])
    tracker.note_event(_ls(_CASE_DIR + "/"))
    assert tracker.unreferenced() == [f"{_CASE_DIR}/fixture.py"]  # input alone: no
    tracker.note_event(_result(
        "total 8\n-rw-r--r--  1 u  staff  12 Sep 24 01:00 fixture.py\n"))
    assert tracker.rejection() == ""


def test_a_listing_that_does_not_name_the_cut_file_leaves_it_required():
    required = [f"{_CASE_DIR}/fixture.py", f"{_CASE_DIR}/other.py"]
    tracker = InspectionTracker(required)
    tracker.note_event(_ls(_CASE_DIR))
    tracker.note_event(_result("other.py\nfixture.py.orig\nREADME.md\n"))
    assert tracker.unreferenced() == [f"{_CASE_DIR}/fixture.py"]


def test_a_listing_credits_only_the_directory_the_call_named():
    tracker = InspectionTracker([f"{_CASE_DIR}/fixture.py"])
    tracker.note_event(_ls("eval/reviewer_recall/cases/some-case"))  # the PARENT
    tracker.note_event(_result("base\nfixture.py\n"))
    assert tracker.unreferenced() == [f"{_CASE_DIR}/fixture.py"]


def test_an_errored_or_unpaired_listing_credits_nothing():
    path = f"{_CASE_DIR}/fixture.py"
    errored = InspectionTracker([path])
    errored.note_event(_ls(_CASE_DIR))
    errored.note_event(_result("fixture.py", is_error=True))
    assert errored.unreferenced() == [path]

    unpaired = InspectionTracker([path])
    unpaired.note_event(_ls(_CASE_DIR, tool_use_id="a"))
    unpaired.note_event(_result("fixture.py", tool_use_id="b"))
    assert unpaired.unreferenced() == [path]

    no_call = InspectionTracker([path])
    no_call.note_event(_result("fixture.py"))
    assert no_call.unreferenced() == [path]


async def test_the_reviewer_accepts_a_verdict_whose_listing_named_the_file(tmp_path):
    path = f"{_CASE_DIR}/fixture.py"
    backend = _Backend([_ls(_CASE_DIR), _result("fixture.py\n")])
    decision = await AdversarialReviewer(backend=backend, timeout=1)._agent_review(
        "prompt", tmp_path, max_turns=1, required_inspections=[path])
    assert decision.passed is True
    assert backend.calls == 1


@pytest.mark.real_backend  # exercises the REAL ClaudeBackend.stream
async def test_claude_tool_results_carry_output_in_process_but_never_to_the_sink(
        tmp_path, monkeypatch):
    from claude_agent_sdk import UserMessage
    from claude_agent_sdk.types import ToolResultBlock

    from no_human.agent import claude_backend
    from no_human.core.orchestrator import Orchestrator

    async def _q(*args, **kwargs):
        yield UserMessage(content=[ToolResultBlock(
            tool_use_id="t1", content=[{"type": "text", "text": "fixture.py\n"}])])

    monkeypatch.setattr(claude_backend, "query", lambda *a, **kw: _q())
    backend = claude_backend.ClaudeBackend(model="claude-sonnet-5")
    events = [e async for e in backend.stream("go", cwd=tmp_path, max_turns=5)]
    (result,) = [e for e in events if e.kind == "tool_result"]
    assert result.output == "fixture.py\n"
    assert not result.text

    rows: list[dict] = []
    Orchestrator._reviewer_sink(SimpleNamespace(_sink=rows.append), result)
    assert "fixture.py" not in repr(rows), rows
