"""`resolve_derived_conflict` on a repo WITHOUT `scripts/export_guard.py`
(the inventory backend): repos that carry `scripts/check_release_manifest.py`
regenerate the whole manifest with `--write` and verify with `--strict`.

Root cause this covers (found live 2026-09-04): the resolver hard-required
`scripts/export_guard.py`, so on the public working repo EVERY manifest-only
PR conflict failed mechanically with step 'regenerate' and escalated a
finished task to a human — three tasks in one day. The fix is gated here on
real end-to-end git fixtures, not mocks.

The fixture copies the REAL `scripts/check_release_manifest.py` from this
repo into the scratch repo — the tool is stdlib-only by its own contract and
roots itself via `git rev-parse --show-toplevel` from its own location, so it
runs unmodified in the fixture. `_inventory_argv()` uses `sys.executable` on
an unfrozen build, so no monkeypatch is needed: the tests exercise the exact
argv production runs here.

Bugfix context (found live overnight, blocked PRs #463/#475/#483/#491):
`_inventory_argv` used to fall back to a bare ``"python3"`` literal when
`real_python` returned `None` — the ONE call site in the codebase that never
failed closed. In an `nh-derived-*` resolver worktree that fallback silently
resolved to the system interpreter (no pytest), which crashes
`tests/test_structural_budget.py`'s scanner and gets misreported as a
"timed out" regenerate failure (`NoInterpreterError is EnvironmentError is
OSError`, caught by `_run_inventory`'s existing `except OSError`). The fix
raises `NoInterpreterError` instead of ever returning `"python3"`.

Round two of the same bug (first review of this fix): `real_python` itself
does NOT return `None` in the `nh-derived-*` worktree unless PATH has
NOTHING named python3/python at all — when a pytest-less system interpreter
IS on PATH (the exact 3.9 the ticket names), `real_python` resolves to it
happily, and trusting that non-`None` result was only half the fix.
`_inventory_python` now probes the resolved interpreter with
`_interpreter_has_pytest` (an actual `import pytest` subprocess run) and
raises `NoInterpreterError` when the probe fails, never handing back an
interpreter that cannot run `tests/test_structural_budget.py`'s scanner.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from no_human.vcs import derived_conflict as dc

_REAL_TOOL = Path(__file__).resolve().parents[1] / "scripts" / "check_release_manifest.py"


def _run(args: list[str], *, cwd) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)


def _git(cwd, *args: str) -> subprocess.CompletedProcess:
    return _run(["git", *args], cwd=cwd)


def _write_manifest(work: Path) -> None:
    r = _run([sys.executable, "scripts/check_release_manifest.py", "--write"],
             cwd=work)
    assert r.returncode == 0, f"fixture --write failed:\n{r.stdout}{r.stderr}"


def _repo(tmp_path: Path) -> Path:
    """From-scratch repo + bare origin: one source file, the REAL inventory
    tool at scripts/check_release_manifest.py, NO export_guard.py, and a
    manifest generated by the tool itself."""
    origin = tmp_path / "origin.git"
    work = tmp_path / "work"
    _run(["git", "init", "-q", "--bare", str(origin)], cwd=tmp_path)
    _run(["git", "init", "-q", "-b", "main", str(work)], cwd=tmp_path)
    _git(work, "config", "user.email", "a@example.com")
    _git(work, "config", "user.name", "a")
    (work / "src").mkdir()
    (work / "src" / "base.py").write_text("base\n", encoding="utf-8")
    (work / "scripts").mkdir()
    shutil.copy(_REAL_TOOL, work / "scripts" / "check_release_manifest.py")
    _git(work, "add", "-A")
    _git(work, "commit", "-qm", "init")
    _write_manifest(work)
    _git(work, "add", "RELEASE_MANIFEST.txt")
    _git(work, "commit", "-qm", "pin inventory")
    _git(work, "remote", "add", "origin", str(origin))
    _git(work, "push", "-qu", "origin", "main")
    return work


def _worktree(work: Path, dest: Path, branch: str, base: str = "main") -> None:
    _git(work, "worktree", "add", "-q", "-b", branch, str(dest), base)


def _push_branch(work: Path, wt: Path, branch: str) -> None:
    sha = _git(wt, "rev-parse", "HEAD").stdout.strip()
    _git(work, "push", "-q", "origin", f"{sha}:refs/heads/{branch}")
    _git(work, "branch", "-q", "--set-upstream-to", f"origin/{branch}", branch)


def _conflicting_fixture(tmp_path: Path) -> tuple[Path, str]:
    """feature and main each add a different file and regenerate the whole
    manifest — two full rewrites of the same file collide for real."""
    work = _repo(tmp_path)

    wt = tmp_path / "wt_feature"
    _worktree(work, wt, "feature")
    (wt / "src" / "on_feature.py").write_text("on feature\n", encoding="utf-8")
    _git(wt, "add", "src/on_feature.py")
    _git(wt, "commit", "-qm", "add on_feature.py")
    _write_manifest(wt)
    _git(wt, "add", "RELEASE_MANIFEST.txt")
    _git(wt, "commit", "-qm", "pin on_feature.py")
    _push_branch(work, wt, "feature")

    (work / "src" / "on_main.py").write_text("on main\n", encoding="utf-8")
    _git(work, "add", "src/on_main.py")
    _git(work, "commit", "-qm", "add on_main.py")
    _write_manifest(work)
    _git(work, "add", "RELEASE_MANIFEST.txt")
    _git(work, "commit", "-qm", "pin on_main.py")
    _git(work, "push", "-q", "origin", "HEAD:refs/heads/main")

    base_tip = _git(work, "rev-parse", "origin/main").stdout.strip()
    return work, base_tip


async def test_manifest_conflict_resolves_on_the_inventory_backend(tmp_path):
    work, base_tip = _conflicting_fixture(tmp_path)

    # sanity: the conflict is real and confined to the manifest.
    paths = await dc.conflicting_paths(str(work), "main", "feature")
    assert paths == {"RELEASE_MANIFEST.txt"}

    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert res.ok, f"step={res.step}: {res.detail}"
    assert res.pushed_sha

    # The pushed merge's manifest carries BOTH sides' files and verifies.
    check = tmp_path / "check"
    _run(["git", "clone", "-q", "-b", "feature", str(work / ".git"), str(check)],
         cwd=tmp_path)
    _git(check, "checkout", "-q", res.pushed_sha)
    manifest = (check / "RELEASE_MANIFEST.txt").read_text(encoding="utf-8")
    assert "src/on_feature.py" in manifest and "src/on_main.py" in manifest
    verify = _run([sys.executable, "scripts/check_release_manifest.py"],
                  cwd=check)
    assert verify.returncode == 0, verify.stdout + verify.stderr


def test_a_repo_with_neither_tool_fails_closed(tmp_path):
    work = tmp_path / "bare-work"
    _run(["git", "init", "-q", "-b", "main", str(work)], cwd=tmp_path)
    _git(work, "config", "user.email", "a@example.com")
    _git(work, "config", "user.name", "a")
    (work / "f.txt").write_text("x\n", encoding="utf-8")
    _git(work, "add", "-A")
    _git(work, "commit", "-qm", "init")

    res = dc.resolve_derived_conflict(str(work), "feature", "HEAD")
    assert not res.ok and res.step == "regenerate"
    assert "check_release_manifest.py" in res.detail


def test_classification_eligibility_fails_closed_without_export_guard(tmp_path):
    work = _repo(tmp_path)
    res = dc.resolve_derived_conflict(
        str(work), "feature", "HEAD",
        eligible=dc.DERIVED_ARTEFACTS | {"EXPORT_CLASSIFICATION.txt"})
    assert not res.ok and res.step == "regenerate"
    # A distinctive fragment of the NEW refusal — the tmp_path directory name
    # contains "classification", so a loose substring check would pass on the
    # OLD message too (review finding on the first revision of this test).
    assert "cannot reconcile classification counts" in res.detail


# --- `_inventory_argv` delegates to the one shared interpreter resolver
# --- (`proc.real_python`) instead of re-writing the PyInstaller-frozen
# --- fallback inline a fifth time (issue #402). These pin the delegation
# --- itself, not just the output, because before this fix the module-level
# --- inline fallback already produced an identical-looking argv on the
# --- happy path — only swapping the shared resolver proves it is actually
# --- being called. ----------------------------------------------------------


def test_inventory_argv_delegates_to_the_shared_real_python(monkeypatch):
    monkeypatch.setattr(dc, "real_python", lambda *a: "/opt/marker/python")
    # `/opt/marker/python` is a marker path, not a real interpreter — stub
    # out the `import pytest` probe so this test isolates the delegation
    # seam (does `_inventory_argv` call the shared `real_python`?) from the
    # separate pytest-capability check `_interpreter_has_pytest` performs.
    monkeypatch.setattr(dc, "_interpreter_has_pytest", lambda *a: True)
    assert dc._inventory_argv() == [
        "/opt/marker/python", "scripts/check_release_manifest.py"]


def test_inventory_argv_interpreter_can_import_pytest(tmp_path):
    """The argv `_inventory_argv` actually produces in THIS environment must
    be a real, dependency-carrying interpreter — not merely a Python. Covers
    both call shapes: no worktree (today's production call from
    `_run_inventory` before this fix threaded the path through) and a
    worktree path (the shape `_run_inventory` uses now)."""
    for argv in (dc._inventory_argv(), dc._inventory_argv(tmp_path)):
        proc = subprocess.run([argv[0], "-c", "import pytest"],
                              capture_output=True, text=True)
        assert proc.returncode == 0, proc.stdout + proc.stderr
        assert "No module named" not in proc.stderr


def test_inventory_python_rejects_a_resolved_interpreter_without_pytest(
        monkeypatch, tmp_path):
    """The exact shape the review found still broken: `real_python` doesn't
    return `None` here — it resolves to a REAL, executable, pytest-less
    interpreter (the system 3.9 an `nh-derived-*` resolver worktree finds on
    PATH when there is no worktree `.venv`). Trusting that non-`None` result
    alone reproduces PRs #463/#475/#483/#491 one layer down. A real
    executable is used (not a mocked `subprocess.run`) so the probe itself,
    not a stand-in for it, is what's exercised."""
    pytest_less = tmp_path / "pytest_less_python"
    pytest_less.write_text("#!/bin/sh\nexit 1\n", encoding="utf-8")
    pytest_less.chmod(0o755)
    monkeypatch.setattr(dc, "real_python", lambda *a: str(pytest_less))

    assert dc._interpreter_has_pytest(str(pytest_less)) is False
    with pytest.raises(dc.NoInterpreterError) as exc_info:
        dc._inventory_argv()
    message = str(exc_info.value)
    assert "RELEASE_MANIFEST" in message
    assert "pytest" in message


def test_inventory_argv_raises_when_no_interpreter_resolves(monkeypatch,
                                                             tmp_path):
    """`real_python` resolving to `None` (a frozen build, no python3/python
    on PATH, no worktree `.venv`) must fail closed with a named exception —
    never silently return the `"python3"` literal, which is how PRs
    #463/#475/#483/#491 got stuck: an unverified system interpreter without
    pytest, misreported as a timeout."""
    monkeypatch.setattr(dc, "real_python", lambda *a: None)
    with pytest.raises(dc.NoInterpreterError) as exc_info:
        dc._inventory_argv()
    assert isinstance(exc_info.value, EnvironmentError)
    message = str(exc_info.value)
    assert "RELEASE_MANIFEST" in message
    assert "python" in message
    # No call shape silently produces the literal fallback — with a worktree
    # path threaded through, too.
    with pytest.raises(dc.NoInterpreterError):
        dc._inventory_argv(tmp_path)


def test_manifest_regen_reports_the_missing_interpreter_not_a_timeout(
        tmp_path, monkeypatch):
    """When `real_python` resolves to `None` mid-resolution (simulating the
    `nh-derived-*` temp tree), the regenerate step must name the missing
    interpreter as the cause — never "timed out", which is the
    silent-misattribution shape `NoInterpreterError` exists to prevent (it
    is a DISTINCT `EnvironmentError` subclass so `_run_inventory`'s
    `except (subprocess.TimeoutExpired, OSError)` cannot swallow it into the
    same `None`/"timed out" result a real timeout produces). No exception
    may escape to the caller — `wake.py` awaits this via
    `asyncio.to_thread` and a raised exception there crashes the watcher."""
    work, base_tip = _conflicting_fixture(tmp_path)
    monkeypatch.setattr(dc, "real_python", lambda *a: None)

    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert not res.ok
    assert res.step == "regenerate"
    assert "no Python interpreter" in res.detail
    assert "timed out" not in res.detail


def test_inventory_argv_never_returns_the_frozen_binary_when_frozen(
        monkeypatch, tmp_path):
    """End-to-end through the real resolver (not the delegation seam above):
    frozen shape, `sys.executable` an `nh` stub, PATH holds a python3 — the
    produced argv[0] must be that PATH python3, never the frozen binary."""
    nh = tmp_path / "nh"
    nh.write_text("", encoding="utf-8")
    monkeypatch.setattr(sys, "frozen", True, raising=False)
    monkeypatch.setattr(sys, "executable", str(nh))
    monkeypatch.setattr(shutil, "which",
                         lambda n: f"/usr/bin/{n}" if n == "python3" else None)
    # `/usr/bin/python3` is a stand-in path for this test's purposes — stub
    # the pytest-capability probe so this test isolates the frozen/PATH
    # resolution path from whether that literal path actually carries
    # pytest on the machine running the test.
    monkeypatch.setattr(dc, "_interpreter_has_pytest", lambda *a: True)
    argv = dc._inventory_argv()
    assert argv[0] == "/usr/bin/python3"
    assert argv[0] != str(nh)


async def test_a_write_refusal_is_a_regenerate_failure_not_a_push(tmp_path):
    """Plant a classification file so the tool's own `--write` refuses with
    exit 2 (in this fixture, via its load_unpinnable Refused branch — no
    build_public_export.py beside it; the "would pin N drop-classified
    path(s)" branch exits 2 identically): the resolver must report step
    'regenerate' and push nothing — the same fixture as the happy path,
    one flip."""
    work, base_tip = _conflicting_fixture(tmp_path)
    (work / "EXPORT_CLASSIFICATION.txt").write_text("ship 1 src/base.py\n",
                                                    encoding="utf-8")
    _git(work, "add", "EXPORT_CLASSIFICATION.txt")
    _git(work, "commit", "-qm", "classification appears")
    _git(work, "push", "-q", "origin", "HEAD:refs/heads/main")
    base_tip = _git(work, "rev-parse", "origin/main").stdout.strip()

    before = _git(work, "rev-parse", "origin/feature").stdout.strip()
    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert not res.ok and res.step == "regenerate"
    after = _git(work, "rev-parse", "origin/feature").stdout.strip()
    assert before == after  # nothing was pushed


async def test_manifest_only_conflict_resolves_with_no_markers_and_a_clean_tree(
        tmp_path):
    """The end-to-end shape the bug report describes: a PR whose conflict is
    confined ENTIRELY to RELEASE_MANIFEST.txt must resolve mechanically —
    no conflict markers survive, the merge is clean, and no human
    escalation is needed to land it (the whole point of this module)."""
    work, base_tip = _conflicting_fixture(tmp_path)

    # (a) the conflict is real and confined to the manifest alone.
    paths = await dc.conflicting_paths(str(work), "main", "feature")
    assert paths == {"RELEASE_MANIFEST.txt"}

    res = dc.resolve_derived_conflict(str(work), "feature", base_tip,
                                      remote="origin")
    assert res.ok, f"step={res.step}: {res.detail}"
    assert res.pushed_sha

    # (b) the pushed manifest carries no conflict markers.
    check = tmp_path / "check"
    _run(["git", "clone", "-q", "-b", "feature", str(work / ".git"), str(check)],
         cwd=tmp_path)
    _git(check, "checkout", "-q", res.pushed_sha)
    manifest = (check / "RELEASE_MANIFEST.txt").read_text(encoding="utf-8")
    for marker in ("<<<<<<<", "=======", ">>>>>>>"):
        assert marker not in manifest

    # (c) the checkout is a genuinely clean, unmerged-free tree, and the
    # inventory tool itself is satisfied in --strict mode — i.e. nothing
    # here needs a human to look at it.
    assert dc._unmerged_paths(check) == set()
    status = _git(check, "status", "--porcelain").stdout
    assert status.strip() == ""
    verify = _run([sys.executable, "scripts/check_release_manifest.py",
                  "--strict"], cwd=check)
    assert verify.returncode == 0, verify.stdout + verify.stderr
