"""Blocker handling (PLAN.md Part 22): taxonomy, structured escalation, and the
wake-condition watcher."""

from .answers import (
    answer_record,
    find_stored_answer,
    normalize_question,
    question_hash,
    reuse_record,
)
from .report import (
    blocker_prompt_suffix,
    ci_misconfigured,
    extract_code_mechanisms,
    fallback_blocker,
    is_code_mechanism_supported,
    missing_access,
    notification_line,
    parse_blocker,
    render_report,
)
from .actions import (
    ActionError,
    apply_action,
    is_plan_approval_action,
    is_terminal_action,
)
from .taxonomy import (
    CONSUMED_HUMAN_PROVENANCE,
    HARNESS_ONLY_CATEGORIES,
    HUMAN_GATE_PROVENANCE,
    MACHINE_REQUEUE_PROVENANCE,
    SERVER_STOP_REASON,
    Blocker,
    BlockerCategory,
    BlockerOption,
    Route,
    carried_checkpoint,
    carry_human_hold,
    human_event,
    human_gate_armed,
    is_human_provenance,
    process_actor,
    resume_checkpoint,
    resume_provenance,
    route_for,
    triage,
    user_pause_blocker,
)
from .wake import WakeWatcher, parse_duration
from .send_back import (
    PENDING_KEY,
    REFUSED_AT_KEY,
    REFUSED_GATE_KEY,
    clear_pending_send_back,
    mark_send_back_refused,
    record_pending_send_back,
    refusal_event,
    refusal_note,
    remedy_text,
)

__all__ = [
    "CONSUMED_HUMAN_PROVENANCE",
    "HARNESS_ONLY_CATEGORIES",
    "HUMAN_GATE_PROVENANCE",
    "MACHINE_REQUEUE_PROVENANCE",
    "SERVER_STOP_REASON",
    "ActionError",
    "apply_action",
    "is_plan_approval_action",
    "is_terminal_action",
    "answer_record",
    "find_stored_answer",
    "normalize_question",
    "question_hash",
    "reuse_record",
    "Blocker",
    "BlockerCategory",
    "BlockerOption",
    "Route",
    "carried_checkpoint",
    "carry_human_hold",
    "human_event",
    "human_gate_armed",
    "is_human_provenance",
    "process_actor",
    "resume_checkpoint",
    "resume_provenance",
    "route_for",
    "triage",
    "user_pause_blocker",
    "parse_blocker",
    "render_report",
    "notification_line",
    "fallback_blocker",
    "missing_access",
    "ci_misconfigured",
    "extract_code_mechanisms",
    "is_code_mechanism_supported",
    "blocker_prompt_suffix",
    "WakeWatcher",
    "parse_duration",
    "PENDING_KEY",
    "REFUSED_AT_KEY",
    "REFUSED_GATE_KEY",
    "clear_pending_send_back",
    "mark_send_back_refused",
    "record_pending_send_back",
    "refusal_event",
    "refusal_note",
    "remedy_text",
]
